"""
Single source of truth for the site's UI copy and skills, in UZ/RU/EN.

Projects are NOT here any more — they live in the database (Project model)
and are edited from the admin panel.

This used to live duplicated inside static/portfolio/js/script.js. Now it
lives here once: the view renders the default language server-side (real
HTML, so the site works with JS disabled and is crawlable by search
engines), and the *same* data is serialized to JSON for the client-side
language switcher (UZ/RU/EN) to use — so there is only ever one place to
edit a project description or a piece of copy.
"""

SUPPORTED_LANGUAGES = ("uz", "ru", "en")
DEFAULT_LANGUAGE = "uz"

STRINGS = {
    "uz": {
        "nav_about": "Men haqimda",
        "nav_skills": "Stek",
        "nav_projects": "Loyihalar",
        "nav_contact": "Aloqa",
        "hero_name": "Shohzod",
        "hero_role": "Django backend muhandisi",
        "hero_tagline": "ERP, ko'p-mijozli SaaS va murakkab biznes platformalar — arxitektura, kod, server va xavfsizlik, boshidan production'gacha.",
        "hero_cta_projects": "Loyihalarni ko'rish",
        "hero_cta_contact": "Bog'lanish",
        "about_title": "Men haqimda",
        "about_p1": "Men — O'zbekistonda joylashgan frilanser full-stack dasturchiman. Asosiy yo'nalishim — Django, biroq ishim faqat kod yozish bilan cheklanmaydi: loyihani boshidan oxirigacha, arxitekturadan tortib serverga joylash va uzoq muddatli qo'llab-quvvatlashgacha mustaqil olib boraman.",
        "about_p2": "Bir vaqtning o'zida bir nechta yo'nalishda ishlayman: biznes uchun to'liq qurilgan ERP va SaaS tizimlari, Telegram bot va mini-ilovalar, hamda n8n orqali jarayonlarni avtomatlashtirish. Har bir loyihada real natijaga — production serverda, real foydalanuvchilar bilan ishlaydigan tizimga yetkazishga alohida e'tibor beraman.",
        "fact_location_label": "Manzil",
        "fact_location_value": "O'zbekiston",
        "fact_focus_label": "Yo'nalish",
        "fact_focus_value": "Django & Python",
        "fact_status_label": "Holat",
        "fact_status_value": "Yangi loyihalarga ochiqman",
        "fact_deploy_label": "Infratuzilma",
        "fact_deploy_value": "Hetzner · Cloudflare · Linux",
        "skills_title": "Stek",
        "skills_backend": "Backend",
        "skills_infra": "Infratuzilma va joylashtirish",
        "skills_bots": "Botlar va avtomatlashtirish",
        "skills_frontend": "Frontend",
        "projects_title": "Loyihalar",
        "status_live": "Ishlamoqda",
        "status_dev": "Ishlab chiqilmoqda",
        "status_tool": "Ichki vosita",
        "project_link": "Saytga o'tish",
        "project_code": "Kodni ko'rish",
        "beyond_title": "Kod ortida",
        "beyond_text": "Dasturlashdan tashqari, mahalliy bizneslar uchun ijtimoiy tarmoq boshqaruvi, sun'iy intellekt yordamida reklama vizuallari va Google Ads sozlash bilan ham shug'ullanaman — bu texnik yechimlarga marketing nuqtai nazaridan ham qarashga yordam beradi.",
        "contact_title": "Keling, gaplashaylik",
        "contact_desc": "Yangi loyiha, hamkorlik yoki savolingiz bormi? Quyidagi manzillar orqali murojaat qiling.",
        "contact_email_btn": "Email yozish",
        "contact_email_copy": "Nusxalash",
        "contact_email_copied": "Nusxalandi!",
        "footer_rights": "Barcha huquqlar himoyalangan.",
        "footer_built": "Django bilan qurilgan",
        "badge_label_one": "production'da ishlayotgan loyiha",
        "badge_label_few": "production'da ishlayotgan loyiha",
        "badge_label_many": "production'da ishlayotgan loyiha",
        "featured_label": "Asosiy loyiha",
        "project_highlights": "Asosiy jihatlar",
        "projects_other_title": "Boshqa ishlar",
        "form_title": "Xabar qoldiring",
        "form_name": "Ismingiz",
        "form_contact": "Email, Telegram yoki telefon",
        "form_message": "Xabar",
        "form_message_ph": "Loyiha yoki taklifingiz haqida qisqacha yozing…",
        "form_submit": "Yuborish",
        "form_sending": "Yuborilmoqda…",
        "form_success": "Rahmat! Xabaringiz yetib keldi — tez orada javob beraman.",
        "form_error": "Xabarni yuborib bo'lmadi. Iltimos, maydonlarni tekshiring.",
        "form_rate": "Juda ko'p urinish. Birozdan so'ng qayta urinib ko'ring yoki email yozing.",
        "err_required": "Bu maydonni to'ldiring.",
        "err_too_long": "Matn juda uzun.",
        "contact_or": "Yoki to'g'ridan-to'g'ri:",
        "cmdk_open": "Buyruqlar",
        "cmdk_placeholder": "Bo'lim, til yoki amal nomini yozing…",
        "cmdk_empty": "Hech narsa topilmadi",
        "cmdk_group_nav": "Bo'limlar",
        "cmdk_group_lang": "Til",
        "cmdk_group_actions": "Amallar",
        "cmdk_group_projects": "Loyihalar",
        "cmdk_copy_email": "Emailni nusxalash",
        "cmdk_github": "GitHub profilini ochish",
        "cmdk_hint_nav": "tanlash",
        "cmdk_hint_enter": "ochish",
        "cmdk_hint_esc": "yopish",
        "nav_top": "Bosh qism",
        "skip_link": "Asosiy kontentga o'tish",
        "menu_label": "Menyu",
        "lang_group_label": "Til",
        "hero_headline_pre": "Bizneslar har kuni tayanadigan ",
        "hero_headline_em": "tizimlarni",
        "hero_headline_post": " quraman.",
        "fact_live_label": "Production'da",
        "diagram_title": "Men quradigan tizim — real komponentlar",
        "diagram_hint": "Tugunni tanlang",
        "diagram_default": "Tugunga kursorni olib boring yoki Tab bilan tanlang: har biri loyihalarimda ishlayotgan haqiqiy yechim.",
        "n_browser": "Brauzer",
        "n_pwa": "Xodimlar PWA",
        "n_bot": "Telegram bot",
        "n_cdn": "Cloudflare",
        "n_app": "nginx · gunicorn · Django",
        "n_db": "PostgreSQL",
        "n_db_sub": "schema-per-tenant",
        "n_ai": "Claude API",
        "n_backup": "Zaxira · R2",
        "n_alerts": "Xabarnomalar",
        "d_browser": "Server tomonda render: sahifa JavaScript'siz ham ishlaydi, har til o'z URL'ida.",
        "d_pwa": "Xodimlar uchun o'rnatiladigan ilova: geofence va kamera bilan davomat, mobil panellar.",
        "d_bot": "Telegram orqali bildirishnomalar va mijoz bilan tezkor aloqa.",
        "d_cdn": "DNS, SSL va keshlash; har bir mijozga alohida subdomen.",
        "d_app": "nginx teskari proksi, gunicorn (gthread) va Django: biznes mantiqi, rollar va ruxsatlar.",
        "d_db": "PostgreSQL: har mijoz uchun alohida sxema (django-tenants), migratsiyalar nazorat ostida.",
        "d_ai": "Claude API: tizim ma'lumotlari ustidan savollarga javob beradigan AI-yordamchi.",
        "d_backup": "Media va shifrlangan tungi zaxira tashqi saqlashda; tiklash muntazam tekshiriladi.",
        "d_alerts": "Xatolar va muhim hodisalar darhol Telegramga keladi.",
        "how_title": "Qanday quraman",
        "how1_t": "Avval jarayon, keyin kod",
        "how1_d": "Biznes jarayonini oxirigacha tushunmaguncha model chizmayman: kim nima qiladi va qayerda xato qimmatga tushadi.",
        "how2_t": "Sodda arxitektura",
        "how2_d": "Django o'zi yecha oladigan joyga ortiqcha qatlam qo'shmayman. Kod keyingi dasturchiga ham tushunarli bo'lishi kerak.",
        "how3_t": "Testlar va audit",
        "how3_d": "Muhim o'zgarishlar avtomatik testlar bilan yopiladi; tizimlarni mustaqil audit qilib, topilmalarni oxirigacha yopaman.",
        "how4_t": "Birinchi kundan production",
        "how4_d": "Zaxira, monitoring, HTTPS va xavfsizlik rejada boshidan bor — ishga tushgandan keyin emas.",
        "contact_email_label": "Email",
    },
    "ru": {
        "nav_about": "Обо мне",
        "nav_skills": "Стек",
        "nav_projects": "Проекты",
        "nav_contact": "Контакты",
        "hero_name": "Шохзод",
        "hero_role": "Django backend-инженер",
        "hero_tagline": "ERP, мультитенантные SaaS и сложные бизнес-платформы — архитектура, код, серверы и безопасность, от идеи до продакшена.",
        "hero_cta_projects": "Смотреть проекты",
        "hero_cta_contact": "Связаться",
        "about_title": "Обо мне",
        "about_p1": "Я — фрилансер и full-stack разработчик из Узбекистана. Основной стек — Django, но моя работа не ограничивается только кодом: я веду проект от архитектуры до деплоя на сервер и дальнейшей поддержки.",
        "about_p2": "Одновременно веду несколько направлений: полноценные ERP- и SaaS-системы для бизнеса, Telegram-боты и мини-приложения, а также автоматизацию процессов через n8n. В каждом проекте для меня важен реальный результат — рабочая система на продакшен-сервере с реальными пользователями.",
        "fact_location_label": "Локация",
        "fact_location_value": "Узбекистан",
        "fact_focus_label": "Фокус",
        "fact_focus_value": "Django & Python",
        "fact_status_label": "Статус",
        "fact_status_value": "Открыт для новых проектов",
        "fact_deploy_label": "Инфраструктура",
        "fact_deploy_value": "Hetzner · Cloudflare · Linux",
        "skills_title": "Стек",
        "skills_backend": "Backend",
        "skills_infra": "Инфраструктура и деплой",
        "skills_bots": "Боты и автоматизация",
        "skills_frontend": "Frontend",
        "projects_title": "Проекты",
        "status_live": "В продакшене",
        "status_dev": "В разработке",
        "status_tool": "Внутренний инструмент",
        "project_link": "Перейти на сайт",
        "project_code": "Смотреть код",
        "beyond_title": "Не только код",
        "beyond_text": "Помимо разработки, я также занимаюсь ведением соцсетей, созданием рекламных визуалов с помощью ИИ и настройкой Google Ads для локального бизнеса — это помогает смотреть на технические решения ещё и с точки зрения маркетинга.",
        "contact_title": "Давайте обсудим",
        "contact_desc": "Новый проект, сотрудничество или просто вопрос? Пишите — контакты ниже.",
        "contact_email_btn": "Написать на почту",
        "contact_email_copy": "Скопировать",
        "contact_email_copied": "Скопировано!",
        "footer_rights": "Все права защищены.",
        "footer_built": "Разработано на Django",
        "badge_label_one": "проект в продакшене",
        "badge_label_few": "проекта в продакшене",
        "badge_label_many": "проектов в продакшене",
        "featured_label": "Главный проект",
        "project_highlights": "Ключевое",
        "projects_other_title": "Другие работы",
        "form_title": "Оставьте сообщение",
        "form_name": "Ваше имя",
        "form_contact": "Email, Telegram или телефон",
        "form_message": "Сообщение",
        "form_message_ph": "Коротко опишите проект или предложение…",
        "form_submit": "Отправить",
        "form_sending": "Отправка…",
        "form_success": "Спасибо! Сообщение получено — скоро отвечу.",
        "form_error": "Не удалось отправить. Проверьте поля.",
        "form_rate": "Слишком много попыток. Попробуйте позже или напишите на почту.",
        "err_required": "Заполните это поле.",
        "err_too_long": "Слишком длинный текст.",
        "contact_or": "Или напрямую:",
        "cmdk_open": "Команды",
        "cmdk_placeholder": "Введите раздел, язык или действие…",
        "cmdk_empty": "Ничего не найдено",
        "cmdk_group_nav": "Разделы",
        "cmdk_group_lang": "Язык",
        "cmdk_group_actions": "Действия",
        "cmdk_group_projects": "Проекты",
        "cmdk_copy_email": "Скопировать email",
        "cmdk_github": "Открыть профиль GitHub",
        "cmdk_hint_nav": "выбор",
        "cmdk_hint_enter": "открыть",
        "cmdk_hint_esc": "закрыть",
        "nav_top": "Начало",
        "skip_link": "Перейти к содержимому",
        "menu_label": "Меню",
        "lang_group_label": "Язык",
        "hero_headline_pre": "Строю ",
        "hero_headline_em": "системы",
        "hero_headline_post": ", на которых бизнес работает каждый день.",
        "fact_live_label": "В продакшене",
        "diagram_title": "Система, которую я строю — реальные компоненты",
        "diagram_hint": "Выберите узел",
        "diagram_default": "Наведите курсор на узел или выберите его клавишей Tab: каждый — реальное решение из моих проектов.",
        "n_browser": "Браузер",
        "n_pwa": "PWA персонала",
        "n_bot": "Telegram-бот",
        "n_cdn": "Cloudflare",
        "n_app": "nginx · gunicorn · Django",
        "n_db": "PostgreSQL",
        "n_db_sub": "schema-per-tenant",
        "n_ai": "Claude API",
        "n_backup": "Бэкапы · R2",
        "n_alerts": "Алерты",
        "d_browser": "Серверный рендеринг: страница работает даже без JavaScript, у каждого языка свой URL.",
        "d_pwa": "Устанавливаемое приложение для сотрудников: учёт посещаемости с геозоной и камерой, мобильные панели.",
        "d_bot": "Уведомления через Telegram и быстрая связь с клиентами.",
        "d_cdn": "DNS, SSL и кэширование; отдельный поддомен для каждого клиента.",
        "d_app": "nginx как обратный прокси, gunicorn (gthread) и Django: бизнес-логика, роли и права доступа.",
        "d_db": "PostgreSQL: отдельная схема для каждого клиента (django-tenants), миграции под контролем.",
        "d_ai": "Claude API: ИИ-помощник, отвечающий на вопросы по данным системы.",
        "d_backup": "Медиа и зашифрованные ночные бэкапы во внешнем хранилище; восстановление регулярно проверяется.",
        "d_alerts": "Ошибки и важные события сразу приходят в Telegram.",
        "how_title": "Как я работаю",
        "how1_t": "Сначала процесс, потом код",
        "how1_d": "Не проектирую модели, пока не пойму бизнес-процесс целиком: кто что делает и где ошибка обходится дороже всего.",
        "how2_t": "Простая архитектура",
        "how2_d": "Не добавляю лишних слоёв там, где Django справляется сам. Код должен быть понятен следующему разработчику.",
        "how3_t": "Тесты и аудит",
        "how3_d": "Важные изменения покрываются автотестами; провожу независимый аудит систем и закрываю найденное до конца.",
        "how4_t": "Продакшен с первого дня",
        "how4_d": "Бэкапы, мониторинг, HTTPS и безопасность заложены с самого начала, а не после запуска.",
        "contact_email_label": "Email",
    },
    "en": {
        "nav_about": "About",
        "nav_skills": "Stack",
        "nav_projects": "Projects",
        "nav_contact": "Contact",
        "hero_name": "Shohzod",
        "hero_role": "Django Backend Engineer",
        "hero_tagline": "ERP, multi-tenant SaaS and complex business platforms — architecture, code, servers and security, from first commit to production.",
        "hero_cta_projects": "View projects",
        "hero_cta_contact": "Get in touch",
        "about_title": "About me",
        "about_p1": "I'm a freelance full-stack developer based in Uzbekistan. Django is my core stack, but the work doesn't stop at code — I take projects from architecture through deployment and long-term maintenance.",
        "about_p2": "I usually run a few tracks at once: full business systems (ERP and SaaS), Telegram bots and mini apps, and process automation with n8n. What matters to me on every project is shipping something real — running in production, on a real server, for real users.",
        "fact_location_label": "Location",
        "fact_location_value": "Uzbekistan",
        "fact_focus_label": "Focus",
        "fact_focus_value": "Django & Python",
        "fact_status_label": "Status",
        "fact_status_value": "Open to new projects",
        "fact_deploy_label": "Infrastructure",
        "fact_deploy_value": "Hetzner · Cloudflare · Linux",
        "skills_title": "Stack",
        "skills_backend": "Backend",
        "skills_infra": "Infrastructure & Deployment",
        "skills_bots": "Bots & Automation",
        "skills_frontend": "Frontend",
        "projects_title": "Projects",
        "status_live": "Live",
        "status_dev": "In development",
        "status_tool": "Internal tool",
        "project_link": "Visit site",
        "project_code": "View code",
        "beyond_title": "Beyond the code",
        "beyond_text": "Alongside development, I also handle social media management, AI-generated ad visuals and Google Ads setup for local businesses — it keeps me thinking about technical solutions from a marketing angle too.",
        "contact_title": "Let's talk",
        "contact_desc": "New project, collaboration, or just a question? Reach out through the links below.",
        "contact_email_btn": "Send an email",
        "contact_email_copy": "Copy",
        "contact_email_copied": "Copied!",
        "footer_rights": "All rights reserved.",
        "footer_built": "Built with Django",
        "badge_label_one": "live project in production",
        "badge_label_few": "live projects in production",
        "badge_label_many": "live projects in production",
        "featured_label": "Featured project",
        "project_highlights": "Highlights",
        "projects_other_title": "Other work",
        "form_title": "Send a message",
        "form_name": "Your name",
        "form_contact": "Email, Telegram or phone",
        "form_message": "Message",
        "form_message_ph": "Tell me briefly about your project or offer…",
        "form_submit": "Send",
        "form_sending": "Sending…",
        "form_success": "Thanks! Your message arrived — I'll reply soon.",
        "form_error": "Couldn't send the message. Please check the fields.",
        "form_rate": "Too many attempts. Please try again later or send an email.",
        "err_required": "Please fill in this field.",
        "err_too_long": "This text is too long.",
        "contact_or": "Or directly:",
        "cmdk_open": "Commands",
        "cmdk_placeholder": "Type a section, language or action…",
        "cmdk_empty": "No results",
        "cmdk_group_nav": "Sections",
        "cmdk_group_lang": "Language",
        "cmdk_group_actions": "Actions",
        "cmdk_group_projects": "Projects",
        "cmdk_copy_email": "Copy email",
        "cmdk_github": "Open GitHub profile",
        "cmdk_hint_nav": "navigate",
        "cmdk_hint_enter": "open",
        "cmdk_hint_esc": "close",
        "nav_top": "Top",
        "skip_link": "Skip to content",
        "menu_label": "Menu",
        "lang_group_label": "Language",
        "hero_headline_pre": "I build the ",
        "hero_headline_em": "systems",
        "hero_headline_post": " businesses run on every day.",
        "fact_live_label": "In production",
        "diagram_title": "The system I build — real components",
        "diagram_hint": "Pick a node",
        "diagram_default": "Hover a node or Tab to it: each one is a real solution running in my projects.",
        "n_browser": "Browser",
        "n_pwa": "Staff PWA",
        "n_bot": "Telegram bot",
        "n_cdn": "Cloudflare",
        "n_app": "nginx · gunicorn · Django",
        "n_db": "PostgreSQL",
        "n_db_sub": "schema-per-tenant",
        "n_ai": "Claude API",
        "n_backup": "Backups · R2",
        "n_alerts": "Alerts",
        "d_browser": "Server-side rendering: pages work without JavaScript, and every language has its own URL.",
        "d_pwa": "An installable app for staff: geofenced, camera-verified attendance and mobile dashboards.",
        "d_bot": "Notifications and fast customer contact over Telegram.",
        "d_cdn": "DNS, SSL and caching, with a dedicated subdomain per client.",
        "d_app": "nginx reverse proxy, gunicorn (gthread) and Django: business logic, roles and permissions.",
        "d_db": "PostgreSQL with a schema per client (django-tenants) and controlled migrations.",
        "d_ai": "Claude API: an AI assistant that answers questions over the system's own data.",
        "d_backup": "Media and encrypted nightly backups in external storage, with restores verified regularly.",
        "d_alerts": "Errors and important events reach Telegram immediately.",
        "how_title": "How I build",
        "how1_t": "Process first, code second",
        "how1_d": "I don't draw a data model until I understand the business process end to end: who does what, and where a mistake costs the most.",
        "how2_t": "Simple architecture",
        "how2_d": "No extra layers where Django already does the job. Code should make sense to the next developer.",
        "how3_t": "Tests and audits",
        "how3_d": "Important changes ship with automated tests; I audit my systems independently and close every finding.",
        "how4_t": "Production from day one",
        "how4_d": "Backups, monitoring, HTTPS and security are in the plan from the start, not bolted on after launch.",
        "contact_email_label": "Email",
    },
}

SKILLS = [
    {"key": "skills_backend", "tags": ["Python", "Django", "Django REST Framework", "PostgreSQL", "django-tenants"]},
    {"key": "skills_infra", "tags": ["Linux", "Nginx", "Gunicorn", "Cloudflare", "Docker", "Git"]},
    {"key": "skills_bots", "tags": ["Telegram Bot API", "aiogram", "Claude API", "n8n"]},
    {"key": "skills_frontend", "tags": ["JavaScript", "HTMX", "Tailwind CSS", "PWA"]},
]

def localized_skills(lang):
    """SKILLS with each group's category title resolved for `lang`."""
    strings = STRINGS[lang]
    return [{"title": strings[group["key"]], "tags": group["tags"]} for group in SKILLS]


LANGUAGE_NAMES = {"uz": "O'zbekcha", "ru": "Русский", "en": "English"}
OG_LOCALES = {"uz": "uz_UZ", "ru": "ru_RU", "en": "en_US"}


def plural_key(lang, n):
    """Pick badge_label_one/few/many for `n` (Russian has three plural forms)."""
    if lang == "ru":
        if n % 10 == 1 and n % 100 != 11:
            return "badge_label_one"
        if 2 <= n % 10 <= 4 and not 12 <= n % 100 <= 14:
            return "badge_label_few"
        return "badge_label_many"
    if lang == "en":
        return "badge_label_one" if n == 1 else "badge_label_many"
    return "badge_label_one"
