# Generated by Django 5.2.17 on 2026-08-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("instagram", "Instagram"),
                            ("telegram", "Telegram"),
                            ("facebook", "Facebook"),
                            ("x", "X (Twitter)"),
                            ("linkedin", "LinkedIn"),
                            ("youtube", "YouTube"),
                            ("github", "GitHub"),
                            ("other", "Boshqa"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Faqat platform 'Boshqa' bo'lsa ko'rinadi (masalan: 'Behance').",
                        max_length=50,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="To'liq profil manzili. Bo'sh qoldirsangiz, ikonka ko'rinadi lekin bosilmaydi.",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Ijtimoiy tarmoq",
                "verbose_name_plural": "Ijtimoiy tarmoqlar",
                "ordering": ["order", "id"],
            },
        ),
    ]
