# Generated by Django 5.2.17 on 2026-10-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_default_social_links"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Ism")),
                (
                    "contact",
                    models.CharField(
                        max_length=200,
                        verbose_name="Aloqa (email / Telegram / telefon)",
                    ),
                ),
                ("message", models.TextField(max_length=4000, verbose_name="Xabar")),
                (
                    "lang",
                    models.CharField(blank=True, max_length=2, verbose_name="Til"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Yuborilgan"),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="O'qildi")),
                (
                    "telegram_sent",
                    models.BooleanField(
                        default=False, verbose_name="Telegramga yuborildi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Xabar",
                "verbose_name_plural": "Xabarlar (aloqa formasi)",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=80, unique=True)),
                (
                    "title_uz",
                    models.CharField(max_length=200, verbose_name="Nomi (UZ)"),
                ),
                (
                    "title_ru",
                    models.CharField(max_length=200, verbose_name="Nomi (RU)"),
                ),
                (
                    "title_en",
                    models.CharField(max_length=200, verbose_name="Nomi (EN)"),
                ),
                ("desc_uz", models.TextField(verbose_name="Tavsif (UZ)")),
                ("desc_ru", models.TextField(verbose_name="Tavsif (RU)")),
                ("desc_en", models.TextField(verbose_name="Tavsif (EN)")),
                (
                    "highlights_uz",
                    models.TextField(
                        blank=True,
                        help_text="Har bir qatorga bitta punkt. Faqat 'Asosiy — katta karta' loyihalarda ko'rinadi.",
                        verbose_name="Asosiy jihatlar (UZ)",
                    ),
                ),
                (
                    "highlights_ru",
                    models.TextField(blank=True, verbose_name="Asosiy jihatlar (RU)"),
                ),
                (
                    "highlights_en",
                    models.TextField(blank=True, verbose_name="Asosiy jihatlar (EN)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("live", "Ishlamoqda (production)"),
                            ("dev", "Ishlab chiqilmoqda"),
                            ("tool", "Ichki vosita"),
                        ],
                        default="live",
                        max_length=10,
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("featured", "Asosiy — katta karta"),
                            ("main", "Oddiy karta"),
                            ("other", "Boshqa ishlar — ixcham ro'yxat"),
                        ],
                        default="main",
                        max_length=10,
                    ),
                ),
                ("link", models.URLField(blank=True, verbose_name="Sayt havolasi")),
                ("github", models.URLField(blank=True, verbose_name="GitHub havolasi")),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Vergul bilan ajrating: Django, PostgreSQL, Nginx",
                        max_length=255,
                        verbose_name="Texnologiyalar",
                    ),
                ),
                (
                    "cover",
                    models.ImageField(
                        blank=True,
                        help_text="Skrinshot (tavsiya: 1600×1000, JPG/WebP). Katta kartada ko'rinadi.",
                        upload_to="projects/",
                        verbose_name="Muqova rasmi",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Tartib"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Saytda ko'rsatilsin"
                    ),
                ),
            ],
            options={
                "verbose_name": "Loyiha",
                "verbose_name_plural": "Loyihalar",
                "ordering": ["order", "id"],
            },
        ),
    ]
