# Generated by Django 5.2.17 on 2026-10-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_seed_projects"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="ip_hash",
            field=models.CharField(
                blank=True, db_index=True, editable=False, max_length=64
            ),
        ),
    ]
