# Generated by Django 5.2.17 on 2026-10-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_contactmessage_ip_hash"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginFailure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_hash", models.CharField(db_index=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "Muvaffaqiyatsiz kirish",
                "verbose_name_plural": "Muvaffaqiyatsiz kirishlar",
            },
        ),
        migrations.CreateModel(
            name="SiteProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        default="Shohzod",
                        help_text="Saytda, sarlavhada va Google uchun ma'lumotlarda shu ism ishlatiladi.",
                        max_length=120,
                        verbose_name="To'liq ism",
                    ),
                ),
                (
                    "about_uz",
                    models.TextField(
                        help_text="2–3 jumla. Bo'sh qator — yangi xatboshi.",
                        verbose_name="Men haqimda (UZ)",
                    ),
                ),
                ("about_ru", models.TextField(verbose_name="Men haqimda (RU)")),
                ("about_en", models.TextField(verbose_name="Men haqimda (EN)")),
            ],
            options={
                "verbose_name": "Sayt profili",
                "verbose_name_plural": "Sayt profili",
            },
        ),
        migrations.AddField(
            model_name="project",
            name="facts_en",
            field=models.TextField(blank=True, verbose_name="Raqamlar (EN)"),
        ),
        migrations.AddField(
            model_name="project",
            name="facts_ru",
            field=models.TextField(blank=True, verbose_name="Raqamlar (RU)"),
        ),
        migrations.AddField(
            model_name="project",
            name="facts_uz",
            field=models.TextField(
                blank=True,
                help_text="Har qatorga bitta qisqa fakt, 3 tagacha: '258 test', '8 til'. Kartada ko'rinadi.",
                verbose_name="Raqamlar (UZ)",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="problem_en",
            field=models.TextField(blank=True, verbose_name="Case: vazifa (EN)"),
        ),
        migrations.AddField(
            model_name="project",
            name="problem_ru",
            field=models.TextField(blank=True, verbose_name="Case: vazifa (RU)"),
        ),
        migrations.AddField(
            model_name="project",
            name="problem_uz",
            field=models.TextField(blank=True, verbose_name="Case: vazifa (UZ)"),
        ),
        migrations.AddField(
            model_name="project",
            name="result_en",
            field=models.TextField(blank=True, verbose_name="Case: natija (EN)"),
        ),
        migrations.AddField(
            model_name="project",
            name="result_ru",
            field=models.TextField(blank=True, verbose_name="Case: natija (RU)"),
        ),
        migrations.AddField(
            model_name="project",
            name="result_uz",
            field=models.TextField(blank=True, verbose_name="Case: natija (UZ)"),
        ),
        migrations.AddField(
            model_name="project",
            name="solution_en",
            field=models.TextField(blank=True, verbose_name="Case: yechim (EN)"),
        ),
        migrations.AddField(
            model_name="project",
            name="solution_ru",
            field=models.TextField(blank=True, verbose_name="Case: yechim (RU)"),
        ),
        migrations.AddField(
            model_name="project",
            name="solution_uz",
            field=models.TextField(
                blank=True,
                help_text="Bo'sh qatorlar bilan xatboshilarga ajrating.",
                verbose_name="Case: yechim (UZ)",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="cover",
            field=models.ImageField(
                blank=True,
                help_text="Skrinshot (tavsiya: 1600×1000). Avtomatik ravishda 1600px WebP'ga siqiladi. Case sahifasida ko'rinadi.",
                upload_to="projects/",
                verbose_name="Muqova rasmi",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="desc_en",
            field=models.TextField(verbose_name="Qisqa tavsif (EN)"),
        ),
        migrations.AlterField(
            model_name="project",
            name="desc_ru",
            field=models.TextField(verbose_name="Qisqa tavsif (RU)"),
        ),
        migrations.AlterField(
            model_name="project",
            name="desc_uz",
            field=models.TextField(
                help_text="Bitta jumla — kartada va ro'yxatda ko'rinadi.",
                verbose_name="Qisqa tavsif (UZ)",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="highlights_uz",
            field=models.TextField(
                blank=True,
                help_text="Har bir qatorga bitta punkt. Loyihaning alohida (case) sahifasida ko'rinadi.",
                verbose_name="Asosiy jihatlar (UZ)",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("live", "Ishlamoqda (production)"),
                    ("launch", "Ishga tushirilmoqda"),
                    ("dev", "Ishlab chiqilmoqda"),
                    ("tool", "Ichki vosita"),
                ],
                default="live",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="tier",
            field=models.CharField(
                choices=[
                    ("featured", "Tanlangan — karta"),
                    ("main", "Boshqa ishlar (eski: oddiy karta)"),
                    ("other", "Boshqa ishlar — ixcham ro'yxat"),
                ],
                default="other",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="sociallink",
            name="url",
            field=models.URLField(
                blank=True,
                help_text="To'liq profil manzili. Bo'sh bo'lsa, ikonka saytda ko'rinmaydi.",
            ),
        ),
    ]
