# Generated by Django 5.2.17 on 2026-10-07 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0009_facebook_handle"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_founder",
            field=models.BooleanField(
                default=False,
                help_text="Kartada «Asoschi» belgisi chiqadi, case sahifasida rol «Asoschi» deb ko'rsatiladi.",
                verbose_name="Men asoschiman",
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="now_en",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Hozir nima qilyapman (EN)"
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="now_project",
            field=models.ForeignKey(
                blank=True,
                help_text="Tanlansa, holat yozuvi shu loyihaning case sahifasiga havola bo'ladi.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="portfolio.project",
                verbose_name="Holat yozuvi havolasi",
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="now_ru",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Hozir nima qilyapman (RU)"
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="now_uz",
            field=models.CharField(
                blank=True,
                help_text="Hero'dagi holat yozuvi. Bo'sh bo'lsa: «Yangi loyihalarga ochiqman».",
                max_length=120,
                verbose_name="Hozir nima qilyapman (UZ)",
            ),
        ),
    ]
